### ISSUE TITLE
python_pip says it supportge purge, but doesn't implement it

### ISSUE THREAD

**Issue by krobertson** [poise/python#104]
The pip resource exposes a `:purge` action, however the provider implementation doesn't actually implement it.  When attempting to use purge, end up with an error:

```
NoMethodError: No resource or method named `action_purge' for `Chef::Provider::PythonPip ""'
```

**Comment by coderanger** [comment]
This is now explicitly unsupported in https://github.com/poise/poise-python with appropriate docs.
