### ISSUE TITLE
python_pip action :purge doesn't work

### ISSUE THREAD

**Issue by bricker** [poise/python#108]
The LWRP and documentation for `python_pip` says it supports `:purge` but there is no code to actually perform that action.

```ruby
python_pip "ez_setup" do
  action :purge
end
```

The error:
```NameError: Cannot find a resource for action_purge on ubuntu version 12.04```

**Comment by coderanger** [comment]
This is now more explicitly unsupported in https://github.com/poise/poise-python, with appropriate documentation.
