### ISSUE TITLE
bump version to 1.5.0

### ISSUE THREAD

**Issue by timurb** [poise/python#110]
The cookbook version needs to be bumped to the next minor version (1.4.6 to 1.5.0).

The last commit (https://github.com/poise/python/commit/f6d0837197d09eeed799073758d7c7a341512877) breaks the cookbook working on Ubuntu 12.04 (and a number of other distributions I suspect) as it has version of pip less than 1.3 which does not yet have `pip list` command.
(By breaking I mean the `python_pip install` resource runs always without respect for whether the package is installed or not which may produce undesired upgrades).

This would be ok if the minor-level version changed but not for the patch-level version:
it turns out I can't fork the cookbook and cherry-pick new fixes in it without creating version clash with you upstream.

Could you please bump the minor version for the cookbook?

**Comment by coderanger** [comment]
Closing this out as this cookbook is now deprecated in favor of https://github.com/poise/poise-python.
