### ISSUE TITLE
Does pip install  support pip package installation from requirements file ?

### ISSUE THREAD

**Issue by BAjayKrishna** [poise/python#116]
Current pip install provider https://github.com/poise/python/blob/master/providers/pip.rb#L33-L52 does not support package installation from requirements file. Which is possible through -r option from command line. Is there a plan to provide it in future releases ?

**Comment by asciifaceman** [comment]
What did you find that made you close this?

**Comment by aspyatkin** [comment]
I suppose it was closed because installing from requirements just works.
Here is an example:
```ruby
python_pip '/path/to/project/requirements.txt' do
    user 'nobody'
    group 'nogroup'
    virtualenv 'path/to/project/.virtualenv'
    action :install
    options '-r'
end
```

**Comment by coderanger** [comment]
@aspyatkin Or, with poise-python, `python_requirements '/path/to/project/requirements.txt'`
