### ISSUE TITLE
source installation fails to install to prefix_dir with solo

### ISSUE THREAD

**Issue by f3r3nc** [poise/python#123]
I am using chef-solo to install python to a specific location.
When wrapping the python cookbook, modifying the default prefix_dir is not taking effect unless it's done in solo.json. 

The problem arises due to the loading order of the default attributes.
https://github.com/poise/python/blob/master/attributes/default.rb#L39: 
     
    default['python']['configure_options'] = %W{--prefix=#{python['prefix_dir']}}

Loads first and creates the configure_options from the prefix_dir that is used for the source configuration 
https://github.com/poise/python/blob/master/recipes/source.rb#L23: 

     configure_options = node['python']['configure_options'].join(" ")
  
 and https://github.com/poise/python/blob/master/recipes/source.rb#L49:

      (cd Python-#{version} && ./configure #{configure_options})

Is this intentional? 
It might be more appropriate to calculate the configure_options directly in source.rb.

**Comment by facastagnini** [comment]
This is not a chef-solo problem, it happens in client mode too.

**context**
```
# knife cookbook list | grep python
python                1.4.6

# chef-client version
Starting Chef Client, version 12.0.3

# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.8 (wheezy)
Release:	7.8
Codename:	wheezy

# cat attributes/default.rb
default['python']['install_method'] = 'source'
default['python']['version'] = '3.4.2'
default['python']['checksum'] = '44a3c1ef1c7ca3e4fd25242af80ed72da941203cb4ed1a8c1b724d9078965dd8'
default['python']['prefix_dir'] = '/usr'
```

**Running chef-client**
```
[...]
* bash[build-and-install-python] action run
[...]
Chef Client finished, 4/65 resources updated in 96.680297683 seconds
```

**Expected result:** python3.4.2 should be installed in */usr/bin*.
**Actual result (problem):** python3.4.2 is being installed in */bin* **!!!**
```
# ls -1 /usr/bin/python*
/usr/bin/python
/usr/bin/python2
/usr/bin/python2.7

# ls -1 /bin/python*
/bin/python3
/bin/python3.4
/bin/python3.4-config
/bin/python3.4m
/bin/python3.4m-config
/bin/python3-config
```

**The --prefix parameter is passing an empty value. It should be /usr**
```
code "  tar -zxvf Python-3.4.2.tgz\n  (cd Python-3.4.2 && ./configure --prefix=)\n  (cd Python-3.4.2 && make && make install)\n"
```

**debugging the problem with chef-shell**
```
# chef-shell --client
chef > echo node['python']['prefix_dir']
 => "/usr"
chef > echo  node['python']['configure_options'].join(" ")
 => "--prefix="
```

**FIX: adding the following line to attributes/default.rb to overwrite the bogus default**
```
default['python']['configure_options'] = %W(--prefix=#{node['python']['prefix_dir']})
```


**Now chef-shell shows how the array is being created properly**
```
chef > echo  node['python']['configure_options'].join(" ")
 => "--prefix=/usr"
```

Running chef-client after adding that line fix the issue.

**Comment by facastagnini** [comment]
After a clarification from @coderanger I had to test one more time.

There is something going on with the line:
```
default['python']['configure_options'] = %W{--prefix=#{node['python']['prefix_dir']}}
```

That line fails to pass the --prefix parameter correctly. I end up with */bin/python3*.

If I include that exact line in my cookbook's *attributes/default.rb* then the --prefix is correct and the python binary is installed in */usr/bin/python3*

I try this in a fresh VM, I can reproduce this behavior every time.

**Comment by coderanger** [comment]
Closing this out as this cookbook is now deprecated in favor of https://github.com/poise/poise-python. I'll revisit installation from source in the future.
