### ISSUE TITLE
altinstall does NOT install alternate python correctly.

### ISSUE THREAD

**Issue by danmaor** [poise/python#126]
Hi,
I configured the cookbook to install into /usr with version 2.7.8 (centos 6.5):

The contents of the /usr/bin/py* BEFORE the cookbook ran:
-rwxr-xr-x. 1 root root      78 Jan 22  2014 /usr/bin/pydoc
-rwxr-xr-x. 2 root root    4864 Jan 22  2014 /usr/bin/python
lrwxrwxrwx. 1 root root       6 Sep  3 19:01 /usr/bin/python2 -> python
-rwxr-xr-x. 2 root root    4864 Jan 22  2014 /usr/bin/python2.6

The contents of the /usr/bin/py* AFTER the cookbook ran:
-rwxr-xr-x. 1 root root      78 Oct 26 18:42 /usr/bin/pydoc
lrwxrwxrwx. 1 root root       7 Oct 26 18:43 /usr/bin/python -> python2
lrwxrwxrwx. 1 root root       9 Oct 26 18:43 /usr/bin/python2 -> python2.7
-rwxr-xr-x. 1 root root    4864 Jan 22  2014 /usr/bin/python2.6
-rwxr-xr-x. 1 root root 6221527 Oct 26 18:42 /usr/bin/python2.7
-rwxr-xr-x. 1 root root    1668 Oct 26 18:43 /usr/bin/python2.7-config
lrwxrwxrwx. 1 root root      16 Oct 26 18:43 /usr/bin/python2-config -> python2.7-config
lrwxrwxrwx. 1 root root      14 Oct 26 18:43 /usr/bin/python-config -> python2-config

As you can see, it creates a symlink for /usr/bin/python which points to python2 for some reason.
python2 is a symlink to python2.7 so essentially i now have only 2.7 and no 2.6.6 (which is needed for yum on centos 6.5)

these are the attributes i configured for the environment.
 "python": {
    "version": "2.7.8",
    "install_dir": "/usr",
    "install_method": "source",
    "setuptools_version": "1.4.2",
    "prefix_dir": "/usr",
    "make_options": [
      "altinstall"
    ]
  }

Thanks,
-D

**Comment by coderanger** [comment]
Closing this out as this cookbook is now deprecated. I'll revisit building from source in the future.
