### ISSUE TITLE
get-pip.py got no attribute 'PROTOCOL_SSLv3' error

### ISSUE THREAD

**Issue by czchen** [poise/python#140]
The `AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'` is showed when running get-pip.py. The problem is that the requests package in `get-pip.py` is old one which expects `ssl.PROTOCOL_SSLv3` exists. However, this is not the case because SSLv3 is insecure now and distro likes Debian remove it from OpenSSL using `OPENSSL_NO_SSLv3`. This behavior is compliance with [official Python document](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_SSLv3), and requests upstream had fix not to assume `ssl.PROTOCOL_SSLv3` exists.

Please help to update the content of `get-pip.py` so that the error will not happen, thanks.

**Comment by chantra** [comment]
PR #142 should fix this I believe.

**Comment by czchen** [comment]
:thumbsup:

**Comment by coderanger** [comment]
This is no longer an issue in https://github.com/poise/poise-python as get-pip.py is not bundled.
