### ISSUE TITLE
Latest version of a pip doesn't work

### ISSUE THREAD

**Issue by dgarstang** [poise/python#141]
I have a custom pip hosted on our own pip server.

Using this works fine when node['slice-deployer']['slice_fablib_version'] is a number.

```
python_pip "slice_fablib" do
  virtualenv node['slice-deployer'][:virtualenv_dir]
  options "-i #{node['slice-deployer']['pip_server_url']}"
  version "#{node['slice-deployer']['slice_fablib_version']}"
end
```

However, when node['slice-deployer']['slice_fablib_version'] = 'latest' it doesn't update the version on the host when a new version is available on the pip server. I also tried removing the version attribute. Same result. If a newer version is available, nothing happens. If I explicitly set node['slice-deployer']['slice_fablib_version'] to the latest version available on the pip server, then it works.

This is for v1.4.6.

**Comment by dgarstang** [comment]
Problem still persists, 4 months later.

**Comment by dgarstang** [comment]
It would be AWESOME if this could be fixed.

**Comment by coderanger** [comment]
Upgrade handling is fixed in https://github.com/poise/poise-python, though you would need action :upgrade.
