### ISSUE TITLE
Integration test broken

### ISSUE THREAD

**Issue by facastagnini** [poise/python#145]
The integration tests have been broken for a while, it will be nice if we can fix it.
I am running the tests locally in an effort to fix the issues.
Any help will be appreciated!

**Comment by facastagnini** [comment]
Anyone with write access would you take a look at this?
@coderanger?

**Comment by coderanger** [comment]
There is no one else with write access and fixing the tests is way lower priority than other stuff. This cookbook needs to be gutted, so probably won't spend a lot of time on it until I have a chance to overhaul it. Closing this ticket out as it isn't useful sans PR.
