### ISSUE TITLE
Adding windows support

### ISSUE THREAD

**Issue by kouroshparsa** [poise/python#147]
I'd like to add windows support for the python recipe.

**Comment by coderanger** [comment]
This can now be handled externally by making a provider for `python_runtime` in https://github.com/poise/poise-python. I don't have the resources to test on Windows at this time.

**Comment by brianwallace** [comment]
I know that this cookbook does not support Windows.  Is anyone aware of another community cookbook that handles python, pip, virtualenv installation for the Windows platform?  Is there a recommended approach?

**Comment by coderanger** [comment]
@brianwallace I don't know of any that handle all of those things. As I mentioned, poise-python was designed with this in mind, someone just needs to build a windows provider for `python_runtime`.
