### ISSUE TITLE
Feature: install packages listed in node attribute

### ISSUE THREAD

**Issue by bitmonk** [poise/python#158]
This would be particularly useful for leveraging the python cookbook via kitchenplan to set up developer notebooks, see how the nodejs cookbook similarly supports an 'apps' attribute:

  https://github.com/kitchenplan/chef-nodejs/blob/master/recipes/default.rb

I could see using this in more typical chef environments, but it should not interfere with anyone who doesn't use it.

**Comment by coderanger** [comment]
No plans to add this, use a wrapper cookbook.
