### ISSUE TITLE
Cannot use get-pip.py without an internet connection

### ISSUE THREAD

**Issue by Jamstah** [poise/python#161]
I need to configure servers on a network that does not have access to PyPi.

To install packages, I am fine with:
python_pip <package to install> do
      options "--no-index --find-links <path to my cache>"
end

It works will and is happy to find dependencies from the cache. However, there is currently no way to pass options to get-pip.py, so I have to run it manually. It works from the command line as:
"python get-pip.py --no-index --find-links <path to my cache>"

Can we have a way to pass options to get-pip.py?

**Comment by coderanger** [comment]
https://github.com/poise/poise-python now handles this by allowing you to pass a URL to an internal copy of get-pip.py.
