### ISSUE TITLE
No longer works under chef 11.10.4, causes compile-time error

### ISSUE THREAD

**Issue by djcp** [poise/python#171]
At least on opsworks. I believe this is because the 2.3.0 release of build-essential is not longer compatible with chef 11, and it doesn't look like the build-essential dependency is defined strictly enough in Berksfile and/or metadata.rb.

**Comment by coderanger** [comment]
This cookbook is long-since deprecated, and even if it wasn't this would be something you should handle in your own dependencies.

**Comment by djcp** [comment]
ok. We need to make sure the `awscli` maintainer knows this, then.
