### ISSUE TITLE
Allow idempotent upgrade [COOK-2843]

### ISSUE THREAD

**Issue by docwhat** [poise/python#174]
This is from [COOK-2843](http://tickets.opscode.com/browse/COOK-2843).

Creating a recipe like:

```
python_pip 'diamond' do
  notifies :restart, 'service[diamond]'
  action :upgrade
end
```

Will always do the upgrade and trigger the notifies.  Example output, using `diamond`:

```
Processing python_pip[diamond] action upgrade (docwhat-diamond::default line 29)
Upgrading python_pip[diamond] version from 4.0.435 to latest
```

Even though `4.0.435` is the latest version

The only workaround at the moment is to set a version number.

There was a pull request at one point for this: #38

**Comment by coderanger** [comment]
This cookbook and resource are deprecated. Use `poise-python` and `python_package`, they already handle this correctly.
