### ISSUE TITLE
Alternative python install takes over easy_install

### ISSUE THREAD

**Issue by koertkuipers** [poise/python#175]
I used poise-python to add python3 to a machine that by default only has python 2:

```
python_runtime "3"
```

however after i did this the default easy_install on the path switched from being the python 2 version to the python 3 version. this breaks the easy_install_package, which was used by some other cookbooks and now suddenly started installing things for python3 instead of python2

**Comment by coderanger** [comment]
`easy_install_package` is super deprecated, so I'm not really inclined to fix this. I'm not even sure it could be fixed. Your best bet would be to install PyPy3 instead and put it in a non-standard location. The defaults should work, it installs to `/opt` and doesn't add itself to `$PATH`.
