### ISSUE TITLE
setting python interpreter to 'python 2.7.11'

### ISSUE THREAD

**Issue by aidanmelen** [poise/python#177]
The README states that we can set the python runtime with the following methods: 

```
python_runtime '2'
```

or 

```
python_runtime 'myapp' do
  version '2.7'
end
```

These methods work fine, but are not explicit enough. 

Is it possible to describe the python interpreter to be python **2.7.11** instead of **2.7**? I would like to explicitly set the python runtime to an exact version and not just the recent version of 2.7.

**Comment by coderanger** [comment]
Yep, just do exactly that. Also you filed this against the wrong repo :)
