### ISSUE TITLE
Allow more python_pip options, like --proxy

### ISSUE THREAD

**Issue by jblaine** [poise/python#64]
I can't make any use of python_pip, and therefore cannot make any use of any cookbook that makes use of python_pip (!!!), because it doesn't support the pip --proxy option. :(

**Comment by asciifaceman** [comment]
I just don't think you understand the scope of this. Hardcoding required pip deps in chef is ludicrous for every app it might deploy from git where a tagged versions requirements.txt might vary. But meh, guess I will just draft out an alternative

**Comment by coderanger** [comment]
@asciifaceman Installing using a requirements.txt is fine, just use an execute resource for it.

**Comment by asciifaceman** [comment]
Could you expand a bit on that? I was kind of relying on the readme a bit.
Also sorry if I came off wrong

**Comment by coderanger** [comment]
This is now handed in https://github.com/poise/poise-python via `python_package` and the `#options` property.

**Comment by jblaine** [comment]
Rad. Thanks Noah!
