### ISSUE TITLE
Need to specify pip version

### ISSUE THREAD

**Issue by pburkholder** [poise/python#68]
The default recipe used to install pip 1.4.1. After the upstream released 1.5 on 1/1

http://www.pip-installer.org/en/latest/news.html#id1

our new nodes don't converge because that requires a newer version of setuptools. I don't see any way in the cookbook to specify the pip version. 

Can you add that, or show me what I'm missing?  Thanks, P.

**Comment by kylegibson** [comment]
Couldn't you just use the new version of pip to install a previous version?

```ruby
python_pip 'pip' do
    version '1.4.1'
end
```

**Comment by pburkholder** [comment]
I think this can be closed.
