### ISSUE TITLE
get-pip.py masks errors

### ISSUE THREAD

**Issue by timor-raiman** [poise/python#77]
To reproduce, run:
sudo -u nobody python /var/chef/cache/get-pip.py
echo $?

Expected outcome: an error code is returned.
Actual outcome: success (0) is returned regardless of errors.

The indirect result of this behaviour is that the install-pip action always succeeds. However, if in fact there was an error, subsequent pip resources will fail with something like:

Error executing action `install` on resource 'python_pip[virtualenv]'
Errno::ENOENT
No such file or directory - pip install  virtualenv

**Comment by coderanger** [comment]
Closing this out as https://github.com/poise/poise-python no longer bundles the get-pip.py.
