### ISSUE TITLE
[COOK-4271] - Add ability to send environment vars to pip install to fix encoding issues

### ISSUE THREAD

**Issue by someara** [poise/python#82]
When using the python cookbook to pip install django-pipeline - chef fails with the following error: https://gist.github.com/petecheslock/e3606f1ba6577fc26383
In the setup.py there is the following:  https://github.com/cyberdelia/django-pipeline/blob/master/setup.py#L11 I think somewhat related to this - but maybe not: https://tickets.opscode.com/browse/CHEF-3304 Basically I need a way to send "LC_ALL" => "en_US.UTF-8" (in my scenario) as an attribute to the python_pip resource so that it can deal with the encoding correctly.

**Comment by coderanger** [comment]
This now uses the Chef `shell_out` helpers, so it should get all the Chef-y goodness on locale stuff.
