### ISSUE TITLE
Add support for installing pip using package manager

### ISSUE THREAD

**Issue by eric-tucker** [poise/python#97]
The default installation should always be package where possible.

On Fedora/RHEL, there is a python-pip package which should always be preferred over installing via source/binary.

**Comment by coderanger** [comment]
This will not be supported. Using https://github.com/poise/poise-python you can make a tiny subclass of one of the existing providers (probably `System`) that replaces the `install_pip` logic with the package install of your choice. You might also want to swap out `install_setuptools` and/or `install_virtualenv` for distro packages as you see fit. You can use the inversion options framework to make this work even with other peoples' cookbooks so going to close this out.
