### ISSUE TITLE
Allow python_pip to pass --allow-external and --allow-unverified in order to download externally hosted packages

### ISSUE THREAD

**Issue by ashish91** [poise/python#98]
As of pip 1.5.x, the user is required to add --allow-external and --allow-unverified in order to download a package from an external site. By default python_pip doesn't pass this argument and in pip 1.5.x chef throws error as pip doesn't look into external sites. Here is the pip issue link => https://github.com/pypa/pip/issues/1586 .
In my case I was not able to install pyodbc using chef with pip 1.5, and I had to revert back to pip 1.4.1 after which pyodbc was successfully installed

**Comment by coderanger** [comment]
This is now supported in https://github.com/poise/poise-python via the `#options` property.
